# .streamlit/secrets.toml

# API 서버 주소 (로컬 또는 배포된 URL)
API_BASE_URL = "https://emergencymodel-11108kimsejin.streamlit.app/"

# (선택) 공공데이터 API 키가 API 서버에서 필요하면 여기에도 넣을 수 있음
# OPEN_API_KEY = "MAARFCQ8-MAAR-MAAR-MAAR-MAARFCQ8AO"
